version: "3.7"

services:
  userservice:
    container_name: user_service
    build:
      context: ../
      dockerfile: deployment/userservice/Dockerfile
    ports:
      - "80:8080"
    restart: always
    networks:
      - userservice-network
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - userservice-network
networks:
  userservice-network:
    driver: bridge