info:
  contact: {}
  description: This is a sample server for a user auth service.
  title: User Auth Service API
  version: 0.1.0
paths:
  /refresh-token:
    post:
      consumes:
      - application/json
      description: Refresh Token for User Auth Service
      produces:
      - application/json
      responses:
        "200":
          description: Refresh
          schema:
            type: string
      summary: Refresh Token
  /register:
    post:
      consumes:
      - application/json
      description: Register to User Auth Service
      produces:
      - application/json
      responses:
        "200":
          description: Register
          schema:
            type: string
      summary: Register
swagger: "2.0"
